arb-dir: lib/src/infrastructure/core/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: ["en", "tr", "ar"]
