name: flutter_clean_architecture
description: "A new Flutter architecture project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility
  collection: ^1.19.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2

  # Network
  dio: ^5.4.1

  # Local Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Encryption
  encrypt: ^5.0.3

  # State Management
  provider: ^6.1.1
dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
